/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import MODEL.Check;
import MODEL.HOAT_DONG;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author A715-42G
 */
public class ActivityForm extends javax.swing.JFrame {

    /**
     * Creates new form ActivityForm
     */
    public ActivityForm() {
        initComponents();
        LoadActivities();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartDate = new com.raven.datechooser.DateChooser();
        EndDate = new com.raven.datechooser.DateChooser();
        FilterPnl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        HD_nametxt = new javax.swing.JTextField();
        HD_Loaicmb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        HD_Filterbtn = new javax.swing.JButton();
        StartDatetxt = new javax.swing.JTextField();
        EndDatetxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HD_Tbl = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Khoa_Add_btn = new javax.swing.JButton();
        Khoa_Edit_btn = new javax.swing.JButton();
        Khoa_Delete_btn = new javax.swing.JButton();
        Khoa_Add_btn1 = new javax.swing.JButton();

        StartDate.setDateFormat("dd/MM/yyyy");
        StartDate.setTextRefernce(StartDatetxt);

        EndDate.setDateFormat("dd/MM/yyyy");
        EndDate.setTextRefernce(EndDatetxt);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FilterPnl.setBackground(new java.awt.Color(110, 89, 222));
        FilterPnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(204, 255, 255), java.awt.Color.lightGray, null));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Event :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Type :");

        HD_Loaicmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","Môn học", "Sự kiện", "Dự án"}));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Start Date :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("End Date :");

        HD_Filterbtn.setBackground(new java.awt.Color(153, 153, 255));
        HD_Filterbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HD_Filterbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/icons8-search-25.png"))); // NOI18N
        HD_Filterbtn.setText("Filter");
        HD_Filterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HD_FilterbtnActionPerformed(evt);
            }
        });

        StartDatetxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        StartDatetxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StartDatetxt.setEnabled(false);
        StartDatetxt.setText("");
        EndDatetxt.setText("");

        EndDatetxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EndDatetxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EndDatetxt.setEnabled(false);

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setText("....");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setText("....");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FilterPnlLayout = new javax.swing.GroupLayout(FilterPnl);
        FilterPnl.setLayout(FilterPnlLayout);
        FilterPnlLayout.setHorizontalGroup(
            FilterPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilterPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HD_Filterbtn)
                .addGap(200, 200, 200))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FilterPnlLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(FilterPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FilterPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HD_nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartDatetxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(FilterPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(FilterPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HD_Loaicmb, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FilterPnlLayout.createSequentialGroup()
                        .addComponent(EndDatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(109, 109, 109))
        );
        FilterPnlLayout.setVerticalGroup(
            FilterPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilterPnlLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(FilterPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FilterPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(HD_nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FilterPnlLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(FilterPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(HD_Loaicmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addGroup(FilterPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FilterPnlLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(FilterPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(StartDatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(FilterPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(EndDatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HD_Filterbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        HD_Tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Event", "Type", "Start Date", "End Date"
            }
        ));
        HD_Tbl.setCellSelectionEnabled(true);
        HD_Tbl.setGridColor(new java.awt.Color(204, 204, 204));
        HD_Tbl.setSelectionBackground(new java.awt.Color(110, 89, 222));
        HD_Tbl.setSelectionForeground(new java.awt.Color(255, 255, 255));
        HD_Tbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        HD_Tbl.setShowGrid(true);
        HD_Tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HD_TblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(HD_Tbl);
        HD_Tbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Khoa_Add_btn.setBackground(new java.awt.Color(153, 153, 255));
        Khoa_Add_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Khoa_Add_btn.setText("Add");
        Khoa_Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Khoa_Add_btnActionPerformed(evt);
            }
        });

        Khoa_Edit_btn.setBackground(new java.awt.Color(153, 153, 255));
        Khoa_Edit_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Khoa_Edit_btn.setText("Edit");

        Khoa_Delete_btn.setBackground(new java.awt.Color(153, 153, 255));
        Khoa_Delete_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Khoa_Delete_btn.setText("Delete");

        Khoa_Add_btn1.setBackground(new java.awt.Color(153, 153, 255));
        Khoa_Add_btn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Khoa_Add_btn1.setText("Add new event");
        Khoa_Add_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Khoa_Add_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Khoa_Add_btn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Khoa_Add_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Khoa_Edit_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Khoa_Delete_btn)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Khoa_Add_btn)
                    .addComponent(Khoa_Edit_btn)
                    .addComponent(Khoa_Delete_btn)
                    .addComponent(Khoa_Add_btn1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FilterPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(FilterPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HD_FilterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HD_FilterbtnActionPerformed
        
    }//GEN-LAST:event_HD_FilterbtnActionPerformed

    private void Khoa_Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Khoa_Add_btnActionPerformed
        try {
           
            HOAT_DONG hd = new HOAT_DONG();
            HOAT_DONG temp = new HOAT_DONG();
            temp = (new DAO.DAO_HoatDong()).getBasicHoatDong(HD_nametxt.getText());
            hd.setTenHD(HD_nametxt.getText());
            hd.setLoai((String) HD_Loaicmb.getSelectedItem());
            hd.setNgayBD(Check.StringToDate(StartDatetxt.getText()));
            hd.setNgayKT(Check.StringToDate(EndDatetxt.getText()));
            
            hd.saveBasicHD();
            
            LoadActivities();
        } catch (ParseException ex) {
            Logger.getLogger(ActivityForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Khoa_Add_btnActionPerformed

    private void Khoa_Add_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Khoa_Add_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Khoa_Add_btn1ActionPerformed

    private void HD_TblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HD_TblMouseClicked
        // TODO add your handling code here:
        int index = HD_Tbl.getSelectedRow();
       TableModel model = HD_Tbl.getModel();
       if (index !=-1)
       {
        HD_nametxt.setText( model.getValueAt(index, 0).toString()); 
        HD_Loaicmb.setSelectedItem( model.getValueAt(index, 1));
        StartDatetxt.setText(model.getValueAt(index, 2).toString());
        EndDatetxt.setText(model.getValueAt(index, 3).toString());
       }
    }//GEN-LAST:event_HD_TblMouseClicked
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StartDate.showPopup();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        EndDate.showPopup();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ActivityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ActivityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ActivityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ActivityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ActivityForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.datechooser.DateChooser EndDate;
    private javax.swing.JTextField EndDatetxt;
    private javax.swing.JPanel FilterPnl;
    private javax.swing.JButton HD_Filterbtn;
    private javax.swing.JComboBox<String> HD_Loaicmb;
    private javax.swing.JTable HD_Tbl;
    private javax.swing.JTextField HD_nametxt;
    private javax.swing.JButton Khoa_Add_btn;
    private javax.swing.JButton Khoa_Add_btn1;
    private javax.swing.JButton Khoa_Delete_btn;
    private javax.swing.JButton Khoa_Edit_btn;
    private com.raven.datechooser.DateChooser StartDate;
    private javax.swing.JTextField StartDatetxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void LoadActivities() {
        Clear();
        DefaultTableModel model = (DefaultTableModel) HD_Tbl.getModel();
        ArrayList<HOAT_DONG> ListAct = (new HOAT_DONG()).getListfromDB(0, "", "", "", "", false);
        for (HOAT_DONG hd : ListAct){
            model.addRow(hd.getRowData());
        }
    }

    private void Clear() {
        HD_nametxt.setText("");
        EndDatetxt.setText("");
        StartDatetxt.setText("");
        Check.RemoveTableData((DefaultTableModel) HD_Tbl.getModel());
    }
}
